name: Deploy to GitHub Pages

on:
  push:
    branches: ['main', 'master'] # Запускать деплой при пуше в эту ветку
  workflow_dispatch: # И позволить запускать вручную

# Устанавливаем разрешения GITHUB_TOKEN для деплоя
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Укажите актуальную версию Node.js

      - name: Setup pnpm (или npm/yarn)
        uses: pnpm/action-setup@v2
        with:
          version: 8
        # Если используете npm, удалите этот блок setup pnpm
        if: false
        # Если используете npm, достаточно только Setup Node

      - name: Install dependencies
        run: pnpm install # или pnpm install

      # ВАЖНО: Устанавливаем переменную окружения BASE_URL
      - name: Build Nuxt
        run: |
          # Если ваш проект лежит в корне репозитория (username.github.io)
          pnpm run build

          # Если проект в подпапке (username.github.io/my-project), раскомментируйте строку ниже:
          # BASE_URL=/имя-папки/ npm run build
          # npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Nuxt 4 генерирует статику в папку .output/public
          path: .output/public

  # Деплой
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
